name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install --production=false
      - name: Install lighthouse
        run: sudo npm install -g @lhci/cli
      - name: Run production build
        run: npm run build
      - name: Run Lighthouse CI
        run: lhci autorun
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uig-prod-build
          path: build
